application: steam-limiter
version: 3
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: markupsafe                                                              
  version: latest 

handlers:
- url: /get.*
  static_files: files/steamlimit-0.7.1.0.exe
  upload: files/.*
  mime_type: application/octet-stream
  expiration: "14d"
  http_headers:
    Content-Disposition: attachment; filename="steam-limiter.exe"

- url: /files
  static_dir: files
  mime_type: application/x-binary

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /base\.css
  static_files: base.css
  upload: base\.css

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: .*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.bat
- ^(.*/)?.*\.js
- ^(.*/)?.*\.csv
